name: Pharmacy-Management
on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, Word 
        
  deploy-dev:
   runs-on: ubuntu-latest
   environment:
     name: DEV
     url: 'https://www.uol.com.br/'
   needs: build
   steps:
    - name: Run a one-line script
      run: echo deploy Desenvolvimento
  
  deploy-homologacao:
   runs-on: ubuntu-latest
   environment:
     name: HOMOL
     url: 'https://www.uol.com.br/'
   needs: deploy-dev
   steps:
    - name: Run a one-line script
      run: echo deploy HOMOLOGACAO
      
  deploy-producao:
   runs-on: ubuntu-latest
   environment:
     name: PRD
     url: 'https://www.uol.com.br/'
   needs: deploy-homologacao
   steps:
    - name: Run a one-line script
      run: echo deploy PRODUCAO     
